services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama

volumes:
  ollama_data: